jobs:
  - name: build
    serial: true
    plan:
      - aggregate:
        - get: sources
          trigger: true
        - get: version
          params: {bump: patch}
      - task: compile
        file: sources/ci/compile.yml
      - put: image
        params:
          build: processed
          tag: version/number
      - put: version
        params: {file: version/number}

resources:
  - name: sources
    type: git
    source:
      uri: git@github.com:Sydsvenskan/lambda-resource.git
      branch: ci
      private_key: {{github_deploy_key}}
  - name: image
    type: docker-image
    source:
      email: {{docker_email}}
      username: {{docker_user}}
      password: {{docker_password}}
      repository: hdsydsvenskan/lambda-resource
  - name: version
    type: semver
    source:
      driver: s3
      bucket: {{state_bucket}}
      key: versions/lambda-resource
      access_key_id: {{aws_id}}
      secret_access_key: {{aws_secret}}
      region_name: {{aws_region}}
